platform :ios, '8.0'
inhibit_all_warnings!

target “XYUIFrameworkDemo” do
pod 'AFNetworking'          #网络请求
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'

#键盘遮挡输入框的处理兼容IOS7
pod 'IQKeyboardManager'

#网络图片
pod 'SDWebImage'

#网络动图
pod 'SDWebImage/GIF'

#指示器
pod 'SVProgressHUD'

#ActionSheet
pod 'ActionSheetPicker-3.0'

#图片浏览器
pod 'IDMPhotoBrowser'

#数据库
pod 'LKDBHelper'

#缓存
pod 'YYCache'

#色彩框架 https://github.com/ViccAlexander/Chameleon
pod 'ChameleonFramework'

#快速定位 https://github.com/intuit/LocationManager
pod 'INTULocationManager'

#表单 https://github.com/xmartlabs/XLForm
pod 'XLForm'

#给UIView加上badge https://github.com/cwRichardKim/RKNotificationHub
pod 'RKNotificationHub'

#打印视图控制器的路径
pod 'UIViewController+Swizzled'

#KVO https://github.com/facebook/KVOController
pod 'KVOController'

#搜索https://github.com/ko1o/PYSearch
pod 'PYSearch'

#FlatUI https://github.com/Grouper/FlatUIKit
pod 'FlatUIKit'

#Parallax Header, Sticky Section Header https://github.com/CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout
pod 'CSStickyHeaderFlowLayout'

#Button 转场动画 https://github.com/entotsu/TKSubmitTransition
pod 'TKSubmitTransition'

#列表到详情界面的转场动画 https://github.com/recruit-mp/RMPZoomTransitionAnimator
pod 'RMPZoomTransitionAnimator'

#微博、微信的ActionSheet https://github.com/iTofu/LCActionSheet
pod 'LCActionSheet'

#自定义segment https://github.com/HeshamMegid/HMSegmentedControl
pod 'HMSegmentedControl'

#微信样式webView https://github.com/devedbox/AXWebViewController
pod 'AXWebViewController'

#FlexibleHeightBar https://github.com/bryankeller/BLKFlexibleHeightBar
pod 'BLKFlexibleHeightBar'

#启动广告 https://github.com/CoderZhuXH/XHLaunchAd
pod 'XHLaunchAd'

#引导页 https://github.com/mamaral/Onboard
pod 'Onboard'


# ShareSDK 主模块(必须)
pod 'mob_sharesdk'
# ShareSDK 平台SDK模块
pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
pod 'mob_sharesdk/ShareSDKPlatforms/Copy'
# MobPush
pod 'mob_pushsdk'


# JPush
pod 'JPush'
pod 'JAnalytics'


end
